# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-24 10:06
from __future__ import unicode_literals

from django.db import migrations
import houdini_admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('houdini_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', houdini_admin.models.AdminUserManager()),
            ],
        ),
    ]
