# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-29 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houdini_admin', '0002_auto_20170524_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
