# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='parent',
        ),
        migrations.AddField(
            model_name='role',
            name='parents',
            field=models.ManyToManyField(null=True, related_name='_role_parents_+', to='core.Role'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(null=True, to='core.Permission'),
        ),
    ]
