# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-04 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161230_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='parents',
            field=models.ManyToManyField(blank=True, to='core.Role'),
        ),
    ]
