# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 06:04
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170411_0237'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.HoudiniUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='profiles',
        ),
        migrations.AddField(
            model_name='application',
            name='roles',
            field=models.ManyToManyField(to='core.Role'),
        ),
    ]
