# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170411_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='core.Role'),
        ),
    ]
