# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-11 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolestopermissions',
            old_name='permisions',
            new_name='permissions',
        ),
    ]
