# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houdini_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key_expires',
            new_name='activation_key_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='password_key_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
